### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by HEnquist**

### CODE REVIEW

**Comment by Wang-Yue** [comment]
is there any plan to merge the bh pitch adjust into 2.0? As I look at the code, I believe it's pretty close?

**Comment by HEnquist** [comment]
> is there any plan to merge the bh pitch adjust into 2.0? As I look at the code, I believe it's pretty close?

The plan is to finish and merge this as soon as my second blackhole pr (the one with clock source select) is finished.

**Comment by Wang-Yue** [comment]
> > is there any plan to merge the bh pitch adjust into 2.0? As I look at the code, I believe it's pretty close?
> 
> The plan is to finish and merge this as soon as my second blackhole pr (the one with clock source select) is finished.

so I guess we can include them now?

**Comment by HEnquist** [comment]
There is some work left on the pitch adjust, no promises for when I'll finish it.

**Pull request merged**
