### PR TITLE
Simple patches generated when testing on low-performance system

### PR DESCRIPTION
**Pull request by pavhofman**

### CODE REVIEW

**Comment by HEnquist** [comment]
Thanks, looks great!
I'm working on trying to finish version 3.0 at the moment, which will be a much smaller set of changes than 2.0 was. I'm not sure if it makes sense to make a new 2.0.x release to include this, or just get it into 3.0. That should hopefully be no more than a couple of weeks away.

**Comment by pavhofman** [comment]
None of these patches are crucial, they can easily wait for 3.0. Thanks!

**Comment by HEnquist** [comment]
I cherry-picked these changes onto the next30 branch here: https://github.com/HEnquist/camilladsp/pull/339
Can you take a look?

**Comment by HEnquist** [comment]
I merged these changes into the next30 branch, to get included in v3.0. Thanks for the PR!

**Pull request closed without merging**
