### PR TITLE
Remove outdated REW script as REW no longer supports output XML.

### PR DESCRIPTION
**Pull request by Wang-Yue**

### CODE REVIEW

**Comment by HEnquist** [comment]
Hmm what do you mean? I just tried and could export XML from REW 5.20.4.

**Comment by Wang-Yue** [comment]
I only see the option to export "in REW .req binary format". In Export I only see export filters as wav or text. No XML. 
What version are you using? I'm using the Mac version. Maybe I found the wrong place?

**Comment by HEnquist** [comment]
REW 5.20.4 on Linux. 
In the EQ window, select rePhase as equalizer, and then "Save filter coefficients to file" under "Filter Tasks" will save as XML.

**Comment by Wang-Yue** [comment]
LOL... I was looking for XML in the menu and could not found it. Now I see how it works! Many thanks! Lemme close this pull request.

**Pull request closed without merging**
